version: '2'


networks:
  proxy:
    external: true

services:

  hello-rest-h2:
    image: uportal/hello-rest:latest
    labels:
      - "traefik.backend=hello-rest-h2"
      - "traefik.frontend.rule=Host:hello-rest-h2.united-portal.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.enable=true"

    restart: always
    networks:
      - proxy
    environment:
      APP_NAME: Hello Rest with H2
      ACTIVE_PROFILES: dev,h2

